- manifests/puppetserver.pp
As per Sup-346 this is to include puppetserver metrics for versions < 2018.1.0
> Sup-346 update to include puppetserver metrics for versions < 2018.1.0

- templates/tidy_cron.epp
When a large number of files are being archived xargs might invoke
tar multiple times - overwriting the preceding tar archive. Using
the "--files-from" option to tar instead lets all files be correctly
archived.
> Ensure tidy's tar captures large numbers of files

- metadata.json
Current version of stdlib is 5.2.0, and metadata is < 5.0.0
> Update metadata for current releases of stdlib

- README.md
- files/json2timeseriesdb
- manifests/activemq.pp
- manifests/init.pp
- manifests/orchestrator.pp
- manifests/pe_metric.pp
- manifests/puppetdb.pp
- manifests/puppetserver.pp
- types/metrics_server.pp
This is a rebase of the work done in https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/pull/6 with the addition of a splunk_hec option.
All comments in the original PR should have hopefully been addressed.
Still currently a WIP.
> (PIE-51) Ability to define a metrics server to ship to

- metadata.json
This commit updates the dependency on puppetlabs-stdlib to allow
version 6.x of the module to be used.
> Update puppetlabs-stdlib dependency

- manifests/puppetserver.pp
This commit updates the version checking logic in
puppet_metrics_collector::puppetserver to skip `versioncmp()` when the
`pe_server_version` fact is missing. This change allows the class to
be applied to FOSS nodes without causing a compilation failure.
> Skip versioncmp when pe_server_version is missing

- functions/hosts_with_pe_profile.pp
The 127.0.0.1 thing is a holdover from before we defaulted to smart configuration of metrics collection. It isn't good UX to use that name though. We should remove it from the defaults so that users don't need to know about or be confused by this legacy 127.0.0.1 thing.
> Remove 127.0.0.1 special case naming

- .rubocop.yml
- files/generate_system_metrics
The script is intended to be used as part of an optional feature to get system stats the same way other stats are gathered and managed.
It uses sar which will poll every x seconds and generate an average, which can then be captured into a file at the same interval as the puppet-metrics-collector polling interval.  This keeps the total data down while not missing things that cause short duration spikes (like compiles that last 6 seconds).  Initial use will be in performance testing.
> (SLV-653) Add a script for generating system stats

- files/generate_system_metrics
Prior to this commit, the metrics timestamp key name in the output file
was `time_stamp_obj`, which caused failures when processing with
`json2timeseries.rb` this commit updates the key to be `timestamp` to
ensure compatibility with the processing scripts.
Processing script:
https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/blob/master/files/json2timeseriesdb#L74
Tk metrics:
https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/blob/master/files/tk_metrics#L152
Along with the timestamp change, this commit changes the output to be floats instead of integers. This allows it to be parsed by the json script as it expects the values to be numeric.
> Update the system metrics timestamp key

- README.md
- files/generate_system_metrics
- manifests/sar_metric.pp
- manifests/system.pp
- manifests/system_cpu.pp
- manifests/system_memory.pp
Depends on https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/pull/28
The new system class is very similar to the init.pp... this is to keep the two seperate during development.
They may get merged in teh future.  But the work flow is such that the master would have puppet metrics collector and sysystem included, while the compilers would only have system.  To merge them would require a clean way to turn off all pe metrics for the compilers.
Also added system_cpu and system_memory to use sar_metric to gather cpu and memory metrics.
> (SLV-672) Add system class to manage system metric

- files/generate_system_metrics
To be consistent with the rest of puppet metrics collector, and to make the errors more findable.
Output them in json format to the output json file.
Also trapped the error that would occur if sar wasn't installed SLV-707
> (SLV-688) send script errors to the output file

- README.md
- files/tk_metrics
- functions/version_based_excludes.pp
- manifests/init.pp
- manifests/orchestrator.pp
- manifests/pe_metric.pp
- manifests/puppetdb.pp
- manifests/puppetserver.pp
Prior to this PR, there was no mechanism for filtering out metrics
from the json files. This PR adds filter capabilities and defaults
to removing the `pe-puppet-profiler` and `file-sync-storage-service`
hashes from the `puppetserver` metrics.
> Allow for excluding data from the metrics files

- files/json2timeseriesdb
This allows the output to have a proper trailing newline.  Otherwise,
when processing multiple files there will be a concatenation of the last
and first lines of each file
> Change STDOUT.write to STDOUT.puts

- files/puma_metrics
- files/puma_metrics.rb
- functions/hosts_with_pe_profile.pp
- manifests/ace.pp
- manifests/bolt.pp
- manifests/init.pp
- manifests/puma_metric.pp
With this commit, collect ace and bolt data: metrics and gc metrics.
Since ace-server and bolt-server are installed on the orchestrator hosts,
this reuses $orchestrator_hosts in init.pp.
Collects nothing unless PE is newer than 2019.4.0, in puma_metrics.rb.
Modify to match when ace and bolt status endpoints are enabled in PE.
> (PE-27794) collect data from ace and bolt (puma) services

- files/puma_metrics
Because in cron ...
X-Cron-Env: <PATH=/usr/bin:/bin>
> (bug) use full path to puppet in puma_metrics

- files/generate_system_metrics
new metrics from bolt and ace call themselves bolt and ace, where as thier processes are called ace-server and bolt-server.  Updated the generate_system_metrics to change to ace and bolt for consistency.  Makes the graphite2json scripts which process those names cleaner.
> (maint) sync up what bolt and ace are called

- files/generate_system_metrics
- files/json2timeseriesdb
The process data gathering greps process names for the ones we wanted to track... then passes the list to sar to track.  If a process passed to sar exists when sar starts, but exits before sar gathers the first round of data, then sar will crash while printing the average summaries.  Thus we lose data.
Also, if the process exited before sar ran, there would be no data and some of the generate_system_metrics code would crash expecting to find that process in the sar results.
Fine tuned the process grep to avoid matching processes we don't care about.
Put a catch to not crash if one of the processes we expect doesn't have any data.
> (SLV-771) Fix bug where process data is missed

- files/amq_metrics
- files/puma_metrics
- files/tk_metrics
This commit updates the scripts that collect metrics from multiple
hosts, amq_metrics, puma_metrics, and tk_metrics, to write each
dataset to STDOUT with a trailing newline. The resulting output
stream is therefore in line-delimited JSON format, which is easy
to parse.
Prior to this commit, datasets from multiple hosts were mashed together
without separators, which was difficult to parse when used as input
for other scripts.
> (PIE-178) Print metrics as line-delimited JSON

- files/json2timeseriesdb
Prior to this commit, the json2timeseriesdb script would fail with the
STDIN input method. The collection script outputs multiple newline
delimited hashes, which caused the JSON parser to fail. This commit
updates the json2timeseriesdb script to be able to handle this input
format.
This can be tested by configuring the metrics collector to ship metrics to a dashboard with something like the following.
```
class {'puppet_metrics_collector':
metrics_server_type => 'influxdb',
metrics_server_hostname => 'pe-201911-agent.puppetdebug.vlan',
metrics_server_db_name => 'puppet_metrics',
}
```
It fixes the issue when there are multiple masters that are bundled into the same output.
> Allow for handling multiple hashes with STDIN

- files/json2timeseriesdb
Do not check ARGF.filename for '-' as (empirically) it always contains '-'
Actually, do not use ARGF as OptionParser.parse! will remove all of its options
from ARGV, leaving only (optional) filenames.
In addition, this guards against STDIN and '-' mismatches,
and handles STDIN in the main data_files loop.
> (bug) Use ARGV instead of ARGF

- files/json2timeseriesdb
Needs to be merged at the same time as https://github.com/puppetlabs/puppet_metrics_dashboard/pull/89
That will update the graphs to consume the date this will now produce
Fixed regex that looked for puppet_server instead of puppetserver
Added regex's for bolt and ace
This means all of the services consistently get replaced and tagged instead of just some.
removed the gc-stats regex as it wasn't used and was making it harder to make graphs using it.
> (SLV-767) Updated measurement tagging

- files/metrics_tidy
In this commit, we create a temp file to hold stdout and stderr.  We set
a trap on error, which will send the temp file to stdout.  This has the
effect of sending the output upon error to mail when run via cron.
> Better error handling in tidy script

- README.md
- files/pe_metrics.rb
- files/tk_metrics
- manifests/pe_metric.pp
- manifests/service/activemq.pp
- manifests/service/puppetdb.pp
- manifests/service/puppetserver.pp
- metadata.json
With this commit ...
We switch from the v1 to v2 Metrics API for additional metrics (for PuppetDB),
and drop metrics for unsupported versions of PE.
(This is required in response to PE-28451 / PE-28468.
Note these additional metrics generate errors in PE 2019.4 via v2:
puppetlabs.puppetdb.ha:name=failed-request-counter
puppetlabs.puppetdb.mq:name=global.generate-retry-message-time
puppetlabs.puppetdb.mq:name=global.retry-persistence-time
> (PE-28451) switch from the v1 to v2 metrics api

- files/metrics_tidy
- files/system_metrics
This PR reduces the file size on disk by doing the following things:
* Fixes a bug where the tarballs files would contain 90 days worth of files instead of 1
* Ensure the system metrics can be tidied up
* Stop pretty-printing the system metrics.
> Reduce the size of files on disk

- files/pe_metrics.rb
Prior to this commit, the coalesce method would not properly handle
boolean values. It would return the default `true` if coalescing a
`false` value. This commit updates the logic to be able to handle
booleans correctly.
This PR resolves #60
> Allow for coalescing boolean values

- manifests/service/orchestrator.pp
`puppet_metrics_collector::service::orchestrator ` class was using `puppetserver` values for its parameters. This corrects that.
> Getting orchestrator paramaters to use correct values, not puppetserver's

- .rubocop.yml
- .sync.yml
- files/metrics_tidy
- files/vmware_metrics
- lib/facter/puppet_metrics_collector.rb
- manifests/sar_metric.pp
- manifests/system.pp
- manifests/system/vmware.pp
- spec/classes/puppet_metrics_collector_system_spec.rb
This changeset updates the `puppet_metrics_collector::system` class to include collection of VMware metrics if `facter virtual` reports `"vmware"`. Collection is done via `vmware-toolbox-cmd stat` and includes:
- session: The VM session ID along with uptime since being booted or migrated along with ESXi version info.
- host: Information about the hypervisor, CPU counts and frequencies.
- resources: CPU and memory resources allocated to the VM. Shows CPU time that has been lost to hypervisor overprovisioning and overhead along with memory usage, memory swapping, memory lost to ESXi ballooning, and NUMA distribution.
- vscsi: I/O performance for each virtual disk attached to the VM.
- vnet: I/O performance for each virtual NIC attached to the VM.
> (SUP-2054) Add VMware metrics collection

- manifests/pe_metric.pp
- manifests/sar_metric.pp
This commit updates the `pe_metric` and `sar_metric` types to use
`force => true` when ensuring to absent. This change allows non-empty
directories to be removed.
> Fix ensure => absent for metrics

- manifests/init.pp
- spec/classes/init_spec.rb
If the `puppet_metrics_collector::system` class is evaluated before the
`puppet_metrics_collector` class, a duplicate declaration error will
occur for output directories and scripts that are common to both classes.
The `system` class has guard logic to prevent this issue, this commit
copies the same logic to the top-level `puppet_metrics_collector` class
and updates the tests to ensure both orderings compile.
> Fix duplicate declaration of common files

- files/metrics_tidy
- files/psql_metrics
- files/vmware_metrics
- lib/facter/puppet_metrics_collector.rb
- manifests/system.pp
- manifests/system/postgres.pp
- spec/classes/puppet_metrics_collector_system_spec.rb
This changeset updates the `puppet_metrics_collector::system` class to gather metrics from the `pe-postgresql` service if the `/opt/puppetlabs/server/bin/psql` executable is present.
This iteration collects the following data:
- Checkpoint activity from `pg_stat_bgwriter`.
- Details of the oldest open transaction from `pg_stat_activity`.
- Connection counts grouped by status (`idle`, `active`, etc.)
along with the maximum number of connections allowed.
- Primary replica status from `pg_replication_slots`.
- For each database:
- Secondary replica status from `pglogical.subscription`.
- Database statistics from `pg_stat_database`.
- Table statistics from `pg_stat_all_tables` and `pg_statio_all_tables`
for each user-facing table with more than 16 kB of data stored.
- Index statistics from …
> (SUP-2058) Gather metrics from pe-postgresql

- files/pe_metrics.rb
Prior to this commit, when an mbean was missing and error would be
logged. This commit changes the default for additional metrics to return
a null when the mbean returns a 404.
Resolved #74
> (GH-74) Return null when a mbean is missing

- manifests/pe_metric.pp
Prior to this commit, a warning would be presented when shipping metrics
using the json2timeseriesdb streaming. This commit adds a - to the command to stop the warning.
Resolves #73
> (gh-73) Append - to the metric command for json2timeseriesdb

- files/psql_metrics
This commit updates the psql_metrics collection script to fix an
issue with error checking. Previously, the script sanitized the
hostname that output data was stored under by replacing "." characters
with "-" characters. But, the error checking routine attempted to
look up data using the un-sanitized hostname. This caused error
checking to always register a failure even when data collection
was successful, which resulted in email spam from cron.
> Fix psql_metrics error checking

- files/json2timeseriesdb
This commit updates the `json2timeseriesdb` script with InfluxDB tagging
logic for the output of the `psql_metrics` script. Tags are generated
for the following attributes:
- Database name
- Table, toast table, or index name
- Replication slot name
Ref. puppetlabs/puppetlabs-puppet_metrics_collector#71
> (SUP-2195) Update json2timeseriesdb to tag Postgres metrics

- files/pe_metrics.rb
- files/tk_metrics
Prior to this commit, all trapperkeeper metrics were not using the
client ssl certificate. With the changes in PE-28647 to enable
authentication in metrics collection, we now need to leverage the
`auth.conf` rules which require client ssl authentication. This commit
defaults to using the client ssl for all tk metrics.
Resolves #81 
This affects PuppetDB collection on both 2021 and 2019.8.5. This PR needs to be tested on previous versions to confirm it does not break the existing PuppetDB metrics collection.
> (GH-81) Enable client ssl cert for metrics

- metadata.json
Prior to this commit, the limit for puppetlabs-stdlib was 7.0.0. stdlib
7.0.0 was recently released and is still compatible with this module.
This commit increased the upper limit for puppetlabs-stdlib to 8.0.0.
> (maint) Increase upper limit on stdlib

- README.md
- files/pe_metrics.rb
- manifests/pe_metric.pp
- spec/defines/pe_metric_spec.rb
This commit updates the collection of metrics from JVM services,
Puppet Server, PuppetDB, etc., to allow remote collection of
data from the `/metrics/v2/api` if the PE version is 2019.8.5
or newer. Remote collection from this API was disabled due
to the fix for CVE-2020-7943, which caused the API to return
a failure response for requests that did not originate from
localhost.
The restriction may also be removed by setting the following
Hiera parameter, which may be useful for FOSS users or users
on older PE versions:
```
puppet_metrics_collector::pe_metric::remote_metrics_enabled: true
```
> (PE-31705) Re-enable remote metric collection

- files/metrics_tidy
Although there is code in place to clean up the temp files when we exit with an error, there is nothing to clean up these files on a clean exit. Ironic for a script called metrics_tidy :)
> Clean up temp files when metrics_tidy exits cleanly

- files/metrics_tidy
In the case of an error or if the files were otherwise deleted, the
previous commit would try to delete $tmp twice.  This commit adds an
array to hold the temp file names and deletes them on exit, checking the
existence of each one.
Also check if $metrics_tmp is >0 bytes before running xargs.  It could
be empty if there are no files to tidy.
> Standardize cleanup of temp files

- .fixtures.yml
- functions/hosts_with_pe_profile.pp
- manifests/pe_metric.pp
- manifests/system.pp
- metadata.json
Prior to this commit, this module required puppetlabs-stdlib to be
functional. This commit removes puppetlabs-stdlib as a depencency.
> (PE-31763) Remove the dependency on stdlib

- manifests/service/puppetdb.pp
Prior to this PR, there were no metrics around the jetty thread
pool. This PR adds additional metrics to collect the jetty
`queuedthreadpool` metrics. This allows for looking at the jetty thread
usage in PuppetDB.
Example:
```
"jetty-queuedthreadpool": {
"org.eclipse.jetty.util.thread:id=0,type=queuedthreadpool": {
"availableReservedThreads": 2,
"busyThreads": 7,
"daemon": false,
"detailedDump": false,
"idleThreads": 1,
"idleTimeout": 60000,
"leasedThreads": 6,
"lowOnThreads": false,
"lowThreadsThreshold": 1,
"maxAvailableThreads": 194,
"maxLeasedThreads": 10,
"maxReservedThreads": 4,
"maxThreads": 200,
"minThreads": 8,
"name": "qtp1512214559",
"queueSize": 0,
"readyThreads": 3,
"reservedThreads": -1,
"state": "STARTED",
"stopTimeout": 30000,
"threads": 10,
"threadsPriority": 5, …
```
> Add PuppetDB Jetty thread metrics

- manifests/service/puppetdb.pp
This PR adds some PuppetDB message queuing metrics to the default
collection. The additional metrics add data about the command processing
and queueing within PuppetDB.
> Add PuppetDB message queue metrics

- files/system_metrics
Prior to this commit, the -I argument was not passed with the `pidstat`
command, which resulted in inaccurate results. This commit adds the `-I`
argument to `pidstat` to divide the `%usr` and `%cpu` by the number of
processors.
resolves #95
> (GH-95) Use -I with pidstat with system_processes

- manifests/collect.pp
- manifests/service/ace.pp
- manifests/service/bolt.pp
- manifests/service/orchestrator.pp
- manifests/service/puppetdb.pp
- manifests/service/puppetserver.pp
- manifests/system/cpu.pp
- manifests/system/memory.pp
- manifests/system/postgres.pp
- manifests/system/processes.pp
- manifests/system/vmware.pp
- spec/defines/pe_metric_spec.rb
Prior to this commit, we instantiated the pe_metric defined types with
"puppet_" in their title.  This created issues in the scripts related to
validating the names of the services and output directories.  This
commit changes the defined type to include the "puppet_" prefix.
> Rework namevar of defined types

- spec/acceptance/functions/hosts_with_pe_profile_spec.rb
- spec/acceptance/init_spec.rb
- spec/acceptance/pe_metric_spec.rb
This commit adds some acceptance tests to validate the service status on
the timers, updates some naming conventions, and checks for metrics
collection.
> (maint) Add acceptance tests for the services

- .github/workflows/pe_latest_testing.yml
- .github/workflows/pe_lts_testing.yml
- .gitignore
- .pdkignore
- metadata.json
- spec/spec_helper.rb
This commit updates the PE versions used for acceptance to the latest releases, adds in RHEL8 as a test platform and updates the PDK template to 2.1.1
> PE Version and PDK Update

- metadata.json
This commit removes Puppet 5.x support within the module. Puppet 5.x is
EOL and will no longer be tested in this module.
> (SUP-2493) Remove Puppet 5.x support

- metadata.json
This commit removes support for operating systems that do not use
SystemD. SystemD is a requirement of this module moving forward as the
cron jobs have been replaced with SystemD timers.
> (SUP-2493) Remove support for SysVinit operating systems

- metadata.json
This commit removes OracleLinux-8 and Scientific-8 from the
metadata.json. These operating systems are not in facterdb and cannot be
tested.
Fixes these errors from the spec tests:
```
Warning: Cannot find image for OracleLinux-8
Warning: Cannot find image for Scientific-8
```
> (maint) Remove Oracle 8 and Scientific 8

- lib/facter/puppet_metrics_collector.rb
- manifests/system.pp
- spec/acceptance/pe_metric_spec.rb
- spec/acceptance/pe_system_spec.rb
- spec/classes/puppet_metrics_collector_system_spec.rb
Prior to this PR, the default was to manage the sysstat package by
default. This PR changes the default to not manage the sysstat
package. It includes logic to only include the system metrics collection
classes when the sysstat package is installed and adds a notify when the
packge is not installed.
Resolves #108
> (GH-108) Disable sysstat management by default

- manifests/system.pp
- spec/classes/puppet_metrics_collector_system_spec.rb
Prior to this commit, the system manifest produced a notify event at
warning level if sysstat was unmanaged and uninstalled.  This caused
issues in idempotency testing, so this commit changes it to a WARN entry
in the server logs that does not produce an event.
> Change system notify to warning function

- .github/workflows/auto_release.yml
Prior to this commit, the auto release workflow would always create PRs,
even if the release version had not changed. This commit adds some
conditions to check if the version has changed before submitting the
PRs.
> (SUP-2568) Skip a release if the version has not changed

- functions/hosts_with_pe_profile.pp
- spec/acceptance/functions/hosts_with_pe_profile_spec.rb
- spec/acceptance/pe_metric_spec.rb
Previously, this would set the hosts to ['127.0.0.1'] when storeconfigs was false. This would cause flip flops when running puppet infra configure -> puppet agent -t.  This sets the default to the host certname, since this is what the value will end up being on the primary post-install, preventing this flip flop.
> (maint) Change default for hosts_with_pe_profile when storeconfigs is false

- spec/acceptance/pe_system_spec.rb
- templates/tidy_timer.epp
- templates/timer.epp
Prior to this commit, this property created an unwanted dependency
between the timer and service.  The effect is that starting the timer
will immediately start the service regardless of the schedule.  Removing
this property allows the implicit relationships to work properly.
> (SUP-2682) Remove Requires= property from timers

- files/create-metrics-archive
- files/metrics_tidy
Prior to this PR, the default was to tidy and archive json files using ctime. This was under the assumption it stood for 'creation time' (see #154). It instead means 'change time'. We care about modified time (mtime) so that the timer doesn't reset whenever the inode is touched, even when the contents remain.
> (GH-154) Switch from change time to modify time

- .fixtures.yml
Per recent changes to [GH security](https://github.blog/2021-09-01-improving-git-protocol-security-github/), updated repo source protocols in `.fixures.yaml`.
* Updated `.fixtures.yaml` to move public repo sources from `git` to `https` protocol.
> (SUP-2923) Replace unencrypted git protocol in .fixtures.yml

- lib/facter/puppet_metrics_collector.rb
- manifests/service/puppetserver.pp
Prior to this change, the filesync storage metrics were excluded in all
cases, so there was no way to determine the timing of the filesync
storage operations. This change adds in three metrics for the filesync
storage service to measure the commits, pre-commit, and add-rm times.
> (SUP-3472) Add file sync storage metric collection

- files/pe_metrics.rb
Prior to this commit, an authentication failure would return a single hash instead of an array of hashes, which caused an exception.  This commit uses dig() to check the status and skip nulls.
> (SUP-3681) Check for valid status key in metrics

- files/json2timeseriesdb
- files/metrics_tidy
- manifests/init.pp
- manifests/service/console.pp
- spec/acceptance/pe_metric_spec.rb
- spec/classes/init_spec.rb
Prior to this change, the metrics collector did not collect metrics from the PE console. This change adds metrics collection for the PE console services.
> (SUP-3881) Add collection for PE console services

- .sync.yml
- Gemfile
- metadata.json
Moves to the dev-tools container which has a proper build environment for ruby gems
Pins concurrent ruby to 1.1.10, this can be rolled back after PDK in dev tools goes to 2.6.1
pins latest change log generator
> Make changelog generator work

- manifests/service/puppetserver.pp
Prior to this commit, the mbeans for the additional file sync storage metrics started with 'puppetserver:name=puppetlabs.puppet'; however, the object name of the mbeans include the hostname of the compiling server. This resulted in the api returning 404s and not collecting the metrics.
This commit replaces the 'puppet' part of the name with a glob, which should match correctly.
> (SUP-4126) Fix file sync additional metrics

- files/psql_metrics
This commit cleans up logic in the `psql_metrics` script that supported Postgres versions older than 10.
These versions are all end of life upstream. Puppet Enterprise upgraded to PostgreSQL 11 with the 2019.2 release and Open Source PuppetDB started requiring PostgreSQL 11 with the 7.0.0 release.
> (SUP-4210) Remove logic for EOL Postgres versions

- functions/version_based_excludes.pp
This commit updates the default configuration for Console metrics
collection to exclude the `comidi-route-metrics` dataset.
The console uses heavily parameterized API paths which can result
in this dataset containing several megabytes of information, most
of which is noise. This can consume several hundreds of megabytes
or gigabytes of storage for a day's worth of metrics and can lead
to disk space exhaustion if cleanup is not active.
If needed, this data can be recovered by analyzing the Console
access logs.
> (SUP-4870) Exclude comidi-route-metrics from Console collection

- files/pe_metrics.rb
- Added error handling for converting the metrics to a JSON object
- Outputs the error message for easier debugging and maintenance
> (SUP-5232) Added error handling to JSON conversion of metrics

- files/psql_metrics
This commit removes index bloat estimates added in SUP-2115 from `psql_metrics`. Collection of this data can result in some amount of temporary files written to disk every 5 minutes due to the nested group and sort operations involved. The bloat values generated were also of questionable quality producing both "reasonable" numbers like 50% bloat and absolutely unusable numbers like -230% bloat.
The table bloat estimate is retained as the query there is less complicated, operates directly on postgres page counts and fill percentages, and does not produce the same negative estimates that the index bloat query is generating.
This partially reverts commit 7497949fe8b28f79eca1efa469f239123050ae9e.
> (PE-40043) Remove faulty index bloat statistics

- files/pe_metrics.rb
This commit adds a guard clause to the `retrieve_additional_metrics`
function in `pe_metrics.rb` that ensures the data returned from the
`/metrics` API is of type Array.
Non-conforming data is logged to stderr along with the URL queried
as non-Array responses typically contain error messages that inform
why the request failed.
> (PE-40346) Fix retrieve_additional_metrics error handling
